name: Build and deploy Python app to Azure Web App - locationcostfinder

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        working-directory: ./Backend
        run: |
          python -m venv venv
          source venv/bin/activate
          
      - name: Install dependencies
        working-directory: ./Backend
        run: |
          pip install -r ../requirements.txt
          pip install dj-database-url  # Extra safety if missing in requirements.txt
      
      - name: Debug Database Environment Variable
        run: |
          echo "DATABASE_URL: ${{ secrets.AZURE_POSTGRESQL_CONNECTIONSTRING }}"

      - name: Run Collectstatic
        working-directory: ./Backend
        run: |
          python manage.py collectstatic --noinput || {
            echo "❌ Collectstatic Failed. Check logs for details.";
            exit 1;
          }

      - name: Zip artifact for deployment
        working-directory: ./Backend
        run: |
          zip release.zip ./* -r
          zip release.zip .env  # Ensure .env variables are added if needed

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            Backend/release.zip
            !Backend/venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # Required for requesting the JWT
      contents: read  # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip Backend/release.zip

      - name: Log Environment Variables
        run: |
          echo "CLIENT ID: ${{ secrets.AZURE_CLIENT_ID }}"
          echo "TENANT ID: ${{ secrets.AZURE_TENANT_ID }}"
          echo "SUBSCRIPTION ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          echo "DATABASE_URL: ${{ secrets.AZURE_POSTGRESQL_CONNECTIONSTRING }}"

      - name: Debug Azure CLI Version
        run: az version

      - name: Debug Azure Account Details
        run: az account show || true

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'locationcostfinder'
          slot-name: 'Production'
          startup-command: "gunicorn server_location_map.wsgi:application --bind=0.0.0.0:8000"
        env:
          DATABASE_URL: ${{ secrets.AZURE_POSTGRESQL_CONNECTIONSTRING }}

      - name: Run Migrations with Logs
        run: |
          az webapp ssh --name locationcostfinder --resource-group locationcostfinder_group --command "cd Backend && python manage.py migrate || {
            echo '❌ Database Migration Failed. Checking Database Connectivity Logs...';
            python manage.py dbshell --database default;
          }"

      - name: Check Deployment Logs
        run: |
          az webapp log tail --name locationcostfinder --resource-group locationcostfinder_group --timeout 300 || true
